namespace QParser.Lexer;

public enum DefaultTokenType
{
    Eof = TokenConstants.Eof,
    Epsilon = TokenConstants.Epsilon,
    Unknown = TokenConstants.Unknown,
    Identifier,
    Integer,
    Real,
    Dot,
    Colon,
    Comma,
    Indent,
    Dedent,
    Declare,
    As,
    If,
    Else,
    Then,
    For,
    To,
    Assignment,
    LessThan,
    GreaterThan,
    LessThanOrEqualTo,
    GreaterThanOrEqualTo,
    Equal,
    NotEqual,
    Plus,
    Minus,
    Multiply,
    Divide,
    IntDivide,
    Power,
    BitAnd,
    BitOr,
    OpenParen,
    CloseParen,
    OpenBracket,
    CloseBracket,
    OpenBrace,
    CloseBrace,
    Space,
    Semicolon,
    QuestionMark,
    String,
    Comment
}